// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnica.Desarrollo.Users.Infrastructure;

namespace PruebaTecnica.Desarrollo.Users.API.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaTecnica.Desarrollo.Users.Domain.Entities.RoleEntity", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("RoleId");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            RoleId = "14095c34-9018-40ca-b25b-6d547d1cdf98",
                            Name = "Usuario"
                        },
                        new
                        {
                            RoleId = "991817b6-b223-4f10-9c16-ca4e46fe37a7",
                            Name = "Administrador"
                        });
                });

            modelBuilder.Entity("PruebaTecnica.Desarrollo.Users.Domain.Entities.UserEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Clave");

                    b.Property<string>("RoleEntityRoleId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RolId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("NombreUsuario");

                    b.HasKey("UserId");

                    b.HasIndex("RoleEntityRoleId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PruebaTecnica.Desarrollo.Users.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("PruebaTecnica.Desarrollo.Users.Domain.Entities.RoleEntity", "RoleEntity")
                        .WithMany()
                        .HasForeignKey("RoleEntityRoleId");

                    b.Navigation("RoleEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
